### ISSUE TITLE
No support for revision a03115 

### ISSUE THREAD

**Issue by michaelacosta-rpi** [pimoroni/rpi_ws281x-python#80]
Hardware revision not supported, even after editing rpihw.c before install
Hardware	: BCM2711
Revision	: a03115
Serial		: 
Model		: Raspberry Pi 4 Model B Rev 1.5

**Comment by Gadgetoid** [comment]
Should be fixed as of v4.3.3

**Comment by michaelacosta-rpi** [comment]
I updated and got the same error. I also uninstalled, re-installed, and re-flashed the SD just to be sure. I then went through the same steps to add my revision to rpihw.c with 4.3.3 and got the same error.

**Comment by michaelacosta-rpi** [comment]
FYI 4.3.3 added support for 4GB and 8GB rev 1.5, but not 1GB rev 1.5. 

Rev 0xa03115 is still not supported
